const express = require('express');

const health = require('./health');
const products = require('./products');
const orders = require('./orders');
const auth = require('./auth');
const adminUsers = require('./adminUsers');
const passwordResets = require('./passwordResets');
const supportIssues = require('./supportIssues');
const siteSettings = require('./siteSettings');
const deals = require('./deals');
const reminders = require('./reminders');
const notifications = require('./notifications');
const messages = require('./messages');
const healthReminders = require('./healthReminders');
const analytics = require('./analytics');
const auditLogs = require('./auditLogs');
const permissions = require('./permissions');
const invoices = require('./invoices');
const docs = require('./docs');
const attendance = require('./attendance');
const payments = require('./payments');
const paymentsAnalytics = require('./paymentsAnalytics');
const salarySlips = require('./salarySlips');
const supervisors = require('./supervisors');
const uploads = require('./uploads');
const attendanceAnalytics = require('./attendanceAnalytics');
const holidays = require('./holidays');
const warnings = require('./warnings');
const resignations = require('./resignations');
const experienceLetters = require('./experienceLetters');
const dutyResumptions = require('./dutyResumptions');
const employeeAnalytics = require('./employeeAnalytics');
const assets = require('./assets');
const history = require('./history');
const about = require('./about');
const customerSupport = require('./customerSupport');
const payroll = require('./payroll');
const financeDashboard = require('./financeDashboard');
const expenses = require('./expenses');
const vendors = require('./vendors');
const bank = require('./bank');
const purchaseOrders = require('./purchaseOrders');
const reports = require('./reports');
const helpCenter = require('./helpCenter');

const router = express.Router();

router.use('/health', health);
router.use('/auth', auth);
router.use('/products', products);
router.use('/orders', orders);
router.use('/admin/users', adminUsers);
router.use('/password-resets', passwordResets);
router.use('/support-issues', supportIssues);
router.use('/site-settings', siteSettings);
router.use('/deals', deals);
router.use('/reminders', reminders);
router.use('/notifications', notifications);
router.use('/messages', messages);
router.use('/health-reminders', healthReminders);
router.use('/analytics', analytics);
router.use('/audit-logs', auditLogs);
router.use('/permissions', permissions);
router.use('/invoices', invoices);
router.use('/docs', docs);
router.use('/attendance', attendance);
router.use('/attendance-analytics', attendanceAnalytics);
router.use('/holidays', holidays);
router.use('/payments', payments);
router.use('/payments-analytics', paymentsAnalytics);
router.use('/salary-slips', salarySlips);
router.use('/supervisors', supervisors);
router.use('/uploads', uploads);
router.use('/warnings', warnings);
router.use('/resignations', resignations);
router.use('/experience-letters', experienceLetters);
router.use('/duty-resumptions', dutyResumptions);
router.use('/employee-analytics', employeeAnalytics);
router.use('/assets', assets);
router.use('/history', history);
router.use('/about', about);
router.use('/help-center', helpCenter);
router.use('/customer-support', customerSupport);
router.use('/payroll', payroll);
// Finance module
router.use('/finance/dashboard', financeDashboard);
router.use('/finance/expenses', expenses);
router.use('/finance/vendors', vendors);
router.use('/finance/bank', bank);
router.use('/finance/purchase-orders', purchaseOrders);
router.use('/finance/reports', reports);

module.exports = router;



